name: Frontend CI


on:
 push:
   branches: [main]
 pull_request:
   branches: [main]


jobs:
 frontend:
   runs-on: ubuntu-latest
   defaults:
     run:
       working-directory: client


   steps:
     - uses: actions/checkout@v3
     - run: yarn install
     - run: yarn lint